### ISSUE TITLE
Cellprofiler ExportedSpreadsheet cdv files empty

### ISSUE THREAD

**Issue by khans359** [broadinstitute/cellprofiler-on-Terra#16]
I set up a pipeline to analyze worm images. I wanted to export the image intensity data to a spreadsheet, so I chose to export them as csv files. However, when I open the csv files, they're empty. No data of std intensity, integrated intensity, etc. However, when I was running the pipelines, those measurements were did show up. I have attached my pipeline and also the exported spreadsheets. I hope somebody can help me out.
[MyExpt_Experiment.csv](https://github.com/broadinstitute/cellprofiler-on-Terra/files/9002966/MyExpt_Experiment.csv)

**Comment by carmendv** [comment]
Hi @khans359,
This repo is for workflows and scripts for running a CellProfiler pipeline on Google Cloud hardware (Terra.bio). We are not supporting de design of CellProfiler profiler. There is is a great place for you to ask this questions: [https://forum.image.sc/tags/c/image-analysis/6/cellprofiler]
I hope you find the help you need.
