### ISSUE TITLE
Consider making use of preemptibles configurable for long running tasks

### ISSUE THREAD

**Issue by deflaux** [broadinstitute/cellprofiler-on-Terra#24]
I was recently testing the cytomining workflow and it was preempted after running for 3 hours, and so took an additional 3.5 hours to complete the test.

Preemptibles are currently hardcoded as [the default](https://github.com/broadinstitute/cellprofiler-on-Terra/blob/master/mining/cytomining.wdl#L170) for the cytomining workflow and other workflows in this collection. **Its a good default!** Please also consider allowing use of preemptibles to be optional for long-running workflows such as cytomining and illumination correction. Thanks!!

**Comment by carmendv** [comment]
Preemtibles are now configurable for the long task
