### ISSUE TITLE
Make the WDL imports into local imports

### ISSUE THREAD

**Issue by sjfleming** [broadinstitute/cellprofiler-on-Terra#38]
Dockstore can handle these well.  But I guess it would be a problem for the Broad Methods repository.

However, some of our WDLs still point to the Broad Methods Repository, so if we forget to update them, then even the Dockstore version of the workflows will be using old imports from the Methods Repository, and will not be synced with GitHub.

**Comment by carmendv** [comment]
[cellprofiler_pipeline.wdl](https://github.com/broadinstitute/cellprofiler-on-Terra/blob/master/pipelines/cellprofiler/cellprofiler_pipeline.wdl) still need to be updated and have local imports instead of the ones at the Broad Methods Repository
