### ISSUE TITLE
Consider adding dependency `crcmod` to Docker images.

### ISSUE THREAD

**Issue by deflaux** [broadinstitute/cellprofiler-on-Terra#49]
I noticed the warning below when using image `us.gcr.io/broad-dsde-methods/cytomining:0.0.3` with the cytomining workflow. Consider adding package `crcmod` to this Docker image, and any other Docker images used by these workflows with calls to `gsutil`. Installation instructions are shown via `gsutil help crcmod`.

```
WARNING: gsutil rsync uses hashes when modification time is not available at
both the source and destination. Your crcmod installation isn't using the
module's C extension, so checksumming will run very slowly. If this is your
first rsync since updating gsutil, this rsync can take significantly longer than
usual. For help installing the extension, please see "gsutil help crcmod".
```

**Comment by sjfleming** [comment]
That's a good idea.  Do I have to somehow point `gsutil` to `crcmod`, or it will be able to find and use it automatically?

(The CellProfiler docker image has `gsutil`, but I don't know if they include `crcmod`... that image is maintained by others though, so I don't think there's anything we can do about that one.)

**Comment by carmendv** [comment]
The task that runs cellprofiler do not uses gsutils. 
The ones that use it are:
- `profiling` task in `cytomining` workflow, that uses the image `us.gcr.io/broad-dsde-methods/cytomining:0.0.3
`
- `gsutil_ls` , `gsutil_ls_to_file`, `gsutil_delocalize`, `extract_and_gsutil_rsync` tasks used in the cellpainting workflows. Those 4 tasks use the image `us.gcr.io/broad-dsde-methods/google-cloud-sdk:alpine`

**Comment by sjfleming** [comment]
Oh yeah @carmendv you're right, we are using Cromwell to localize those files during the cellprofiler task

**Comment by sjfleming** [comment]
Now I am forgetting where that `us.gcr.io/broad-dsde-methods/google-cloud-sdk:alpine` image came from... but the name suggests that I made it.  If that's the case, it might also be missing `crcmod`...
I wonder if there's a better, google-hosted image for a slim google cloud SDK?  There must be.  Let me try to see what Cromwell uses

**Comment by sjfleming** [comment]
Nevermind, I checked and the `us.gcr.io/broad-dsde-methods/google-cloud-sdk:alpine` image does have a compiled `crcmod` installed.

I'm thinking that maybe we should test out `us.gcr.io/google.com/cloudsdktool/google-cloud-cli:397.0.0-alpine` and switch to it if it works... if we want... in the future... since that is maintained by google.  Their image is a bit larger (640MB as opposed to 240MB) but I guess it makes no real difference.
